#!/usr/bin/env ansible-playbook
---

- hosts: '!g_poweredoff'
  gather_facts: True
  tasks: [ group_by: { key: 'debian_{{ ansible_distribution_release }}' } ]
  tags: always

- hosts: debian_buster:debian_stretch:debian_jessie:debian_wheezy:debian_precise:debian_trusty
  gather_facts: False
  become: True
  tags: epi

  vars:

    hold_search:
      epi:
        - &epi ?and(?maintainer(epiconcept), ?installed)
      percona: 
        - &percona ~i^percona-xtrabackup$
      apache: &apache ~i^apache2
      mysql: &mysql ~i^mysql-
      php: &php ~i^php5-
      safe: &safe [ *epi, *apache, *mysql, *php ]
      default_to:
        - *epi
      all:
        - *epi
        - *percona

  roles: [ { role: apt-hold } ]
    
  tasks: &tasks

    - apt_hold:
        hold: '{{ hold | default(True) | bool }}'
        search: '{{ search | default(hold_search.default_to) }}'
        notfoundok: '{{ notfoundok | default(False) | bool }}'
      
    - debug: { var: apt_hold }
      when: show | default(False) | bool and apt_hold.diff is defined

    - debug: { var: apt_hold.diff }
      when: not show | default(False) | bool and apt_hold.diff is defined

- hosts: 'debian_jessie:&g_mysql:!all'
  gather_facts: False
  become: True
  tags: percona

  vars:

    hold_search:
      default_to:
        - *percona

  tasks: *tasks

- hosts: debian_buster:debian_stretch:debian_jessie:debian_wheezy:debian_precise:debian_trusty
  gather_facts: False
  become: True
  tags: safe

  vars:

    hold_search:
      default_to: *safe

  tasks: *tasks
