#!/usr/bin/env ansible-playbook
---

- hosts: localhost
  gather_facts: False
  tags: once

  vars: &vars

    data_dir:     ext/data
    data_version: v0.72.0

    data:         '{{ data_dir}}/{{ data_version }}/templates.out'
    local:        '{{ ansible_hostname }}'
    user:         '{{ ansible_user_id }}'

  tasks:

    - set_fact:
        keys:
          - id_epiconcept
          - t.delamare@epiconcept.fr
    - set_fact:
        git_ssh_key_file: |-
          {{ lookup('env', 'GIT_SSH_KEY_FILE') | default('~/.ssh/' ~ keys[1], True) }}

    - git:
        repo: git@github.com:Epiconcept-Paris/infra-data.git
        version: '{{ data_version }}'
        dest: '{{ data_dir}}/{{ data_version }}'
        key_file: '{{ git_ssh_key_file }}'
      when: data_version != 'debug'
      tags: git
      name: get infra-data

- hosts: localhost
  gather_facts: True
  tags: main

  vars: *vars

  tasks:

    - copy:
        src: '{{ data}}/config/ssh-config-{{ local }}-{{ user }}'
        dest: '{{ playbook_dir}}/ssh-config'
        mode: 0444
      name: config

    - copy:
        src: '{{ data}}/inventory/{{ item }}'
        dest: '{{ playbook_dir}}/inventory/{{ item }}.ext'
        mode: 0444
      with_items:
        - ansible_ssh_host
        - networks
        - static_groups
        - poweroff
        - ansible_become_pass_{{ user }}

    - copy:
        src: '{{ data}}/inventory/{{ item }}'
        dest: '{{ playbook_dir}}/inventory/'
        mode: 0444
      with_items:
        - group_vars

      name: inventory

    - file:
        path: '{{ playbook_dir}}/vars/ext'
        state: directory

    - copy:
        src: '{{ data}}/vars/{{ item }}.yml'
        dest: '{{ playbook_dir}}/vars/ext/{{ item }}.yml'
        mode: 0444
      with_items:
        - ips
        - networks
        - vms
      name: vars
