---

# ansible-galaxy install -r requirements.yml
#
# ansible-galaxy collection list
#
# ansible-galaxy collection verify ansible.posix
# ansible-galaxy collection ansible.posix --upgrade
#
# ansible-galaxy collection verify -r requirements.yml
# ansible-galaxy collection install --upgrade -r requirements.yml

collections:
  - ansible.posix
  - ansible.netcommon
  - community.general

roles:
- src: https://github.com/thydel/ar-apt-hold.git
  name: apt-hold

...
